# Generated by Django 2.0.13 on 2019-04-28 19:49

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import stronka.models


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=255)),
                ('MinAge', models.IntegerField(null=True)),
                ('MaxAge', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Forename', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('TelNumber', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('Email', models.EmailField(max_length=50)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronka.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.CharField(max_length=50)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronka.Category')),
                ('IDJudge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stronka.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Passed', models.BooleanField(default=False)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronka.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Register_Date', models.DateField(default=datetime.datetime(2019, 4, 28, 21, 49, 8, 248022))),
                ('City', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=100)),
                ('Country', django_countries.fields.CountryField(default='Poland', max_length=746, multiple=True)),
                ('TeamCode', models.CharField(default=stronka.models.Team.unique_rand, max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Forename', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=4)),
                ('TeamID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stronka.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='robot',
            name='TeamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stronka.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='IDRobot1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot1', to='stronka.Robot'),
        ),
        migrations.AddField(
            model_name='match',
            name='IDRobot2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot2', to='stronka.Robot'),
        ),
    ]
