# Generated by Django 2.0.13 on 2019-04-08 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Register_Date', models.DateField(default=datetime.datetime(2019, 4, 8, 17, 13, 41, 425350))),
                ('City', models.CharField(max_length=50)),
                ('Company', models.CharField(max_length=100)),
            ],
        ),
    ]
