# Generated by Django 2.0.13 on 2019-04-28 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('stronka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 21, 49, 28, 899809)),
        ),
    ]
