# Generated by Django 2.0.13 on 2019-04-08 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0002_auto_20190408_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 8, 17, 15, 35, 673177)),
        ),
    ]
