# Generated by Django 2.0.13 on 2019-04-29 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0003_auto_20190428_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOwn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Forename', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 29, 22, 46, 5, 306986)),
        ),
        migrations.AddField(
            model_name='userown',
            name='TeamID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stronka.Team'),
        ),
        migrations.AddField(
            model_name='userown',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stronka.User'),
        ),
    ]
