# Generated by Django 2.0.13 on 2019-04-09 09:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0005_auto_20190408_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Forename', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='ID',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 11, 7, 1, 553830)),
        ),
        migrations.AddField(
            model_name='user',
            name='TeamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronka.Team'),
        ),
    ]
