# Generated by Django 2.0.13 on 2019-04-09 11:18

import datetime
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0006_auto_20190409_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='Country',
            field=django_countries.fields.CountryField(default='Poland', max_length=746, multiple=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 13, 18, 42, 410476)),
        ),
    ]
