# Generated by Django 2.0.13 on 2019-04-09 11:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0007_auto_20190409_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 13, 22, 5, 918976)),
        ),
        migrations.AlterField(
            model_name='user',
            name='TeamID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stronka.Team'),
        ),
    ]
