# Generated by Django 2.0.13 on 2019-04-09 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0009_auto_20190409_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Size',
            field=models.CharField(choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('XL', 'EXTRALARGE'), ('XXL', 'EXTRAEXTRALARGE')], default='M', max_length=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 14, 50, 36, 303961)),
        ),
    ]
