# Generated by Django 2.0.13 on 2019-05-02 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('stronka', '0010_auto_20190502_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 5, 2, 18, 33, 57, 261849)),
        ),
    ]
