# Generated by Django 2.0.13 on 2019-04-09 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0010_auto_20190409_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 14, 51, 32, 85712)),
        ),
        migrations.AlterField(
            model_name='user',
            name='Size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], default='M', max_length=4),
        ),
    ]
