# Generated by Django 2.0.13 on 2019-05-05 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0011_auto_20190502_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 22, 14, 46, 679227)),
        ),
    ]
