# Generated by Django 2.0.13 on 2019-04-09 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0011_auto_20190409_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=255)),
                ('MinAge', models.IntegerField(null=True)),
                ('MaxAge', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Passed', models.BooleanField(default=False)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronka.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 15, 8, 9, 362845)),
        ),
        migrations.AddField(
            model_name='robot',
            name='TeamID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronka.Team'),
        ),
    ]
