# Generated by Django 2.0.13 on 2019-04-09 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0012_auto_20190409_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 15, 9, 6, 287219)),
        ),
    ]
