# Generated by Django 2.0.13 on 2019-04-09 13:40

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0013_auto_20190409_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Forename', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('TelNumber', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('Email', models.EmailField(max_length=50)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronka.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.CharField(max_length=50)),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronka.Category')),
                ('IDJudge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stronka.Judge')),
                ('IDRobot1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot1', to='stronka.Robot')),
                ('IDRobot2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot2', to='stronka.Robot')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 9, 15, 40, 2, 330264)),
        ),
    ]
