# Generated by Django 2.0.13 on 2019-05-05 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0014_auto_20190505_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 23, 55, 35, 433853)),
        ),
    ]
