# Generated by Django 2.0.13 on 2019-05-05 21:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0015_auto_20190505_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 5, 5, 23, 56, 13, 107685)),
        ),
    ]
