# Generated by Django 2.0.13 on 2019-05-06 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0016_auto_20190505_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userown',
            name='TeamID',
        ),
        migrations.RemoveField(
            model_name='userown',
            name='user',
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 5, 6, 13, 43, 27, 702537)),
        ),
        migrations.DeleteModel(
            name='UserOwn',
        ),
    ]
