# Generated by Django 2.0.13 on 2019-04-24 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0017_auto_20190425_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 25, 1, 3, 15, 446820)),
        ),
    ]
