# Generated by Django 2.0.13 on 2019-05-06 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0017_auto_20190506_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IsJudge',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 5, 6, 13, 44, 9, 695760)),
        ),
    ]
