# Generated by Django 2.0.13 on 2019-06-03 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0018_auto_20190506_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='IDJudge',
        ),
        migrations.AddField(
            model_name='robot',
            name='Group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 3, 16, 18, 33, 426612)),
        ),
    ]
