# Generated by Django 2.0.13 on 2019-04-26 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0019_auto_20190425_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 26, 21, 25, 6, 808921)),
        ),
    ]
