# Generated by Django 2.0.13 on 2019-06-07 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0019_auto_20190603_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='CategoryID',
        ),
        migrations.RemoveField(
            model_name='category',
            name='MaxAge',
        ),
        migrations.RemoveField(
            model_name='category',
            name='MinAge',
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 8, 0, 19, 8, 495666)),
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
