# Generated by Django 2.0.13 on 2019-04-28 17:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0019_auto_20190425_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='TeamID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stronka.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 4, 28, 19, 25, 50, 251107)),
        ),
    ]
