# Generated by Django 2.0.13 on 2019-06-10 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0021_auto_20190608_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 10, 10, 36, 51, 295152)),
        ),
    ]
