# Generated by Django 2.0.13 on 2019-06-10 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0022_auto_20190610_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 10, 12, 6, 31, 89766)),
        ),
    ]
