# Generated by Django 2.0.13 on 2019-06-12 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0024_auto_20190611_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 13, 1, 15, 13, 317857)),
        ),
    ]
