# Generated by Django 2.0.13 on 2019-06-13 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0025_auto_20190613_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Result', models.FloatField()),
                ('CategoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stronka.Category')),
                ('IDRobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robot', to='stronka.Robot')),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 13, 2, 10, 29, 903706)),
        ),
    ]
