# Generated by Django 2.0.13 on 2019-06-13 01:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0026_auto_20190613_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='Type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='CategoryID',
            field=models.ForeignKey(limit_choices_to={'Type': 1}, on_delete=django.db.models.deletion.CASCADE, to='stronka.Category'),
        ),
        migrations.AlterField(
            model_name='race',
            name='CategoryID',
            field=models.ForeignKey(limit_choices_to={'Type': 2}, on_delete=django.db.models.deletion.CASCADE, to='stronka.Category'),
        ),
        migrations.AlterField(
            model_name='race',
            name='IDRobot',
            field=models.ForeignKey(limit_choices_to={'Type': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='robot', to='stronka.Robot'),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 13, 3, 5, 54, 606358)),
        ),
    ]
