# Generated by Django 2.0.13 on 2019-06-13 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0028_auto_20190613_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='Group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 13, 19, 5, 30, 573386)),
        ),
    ]
