# Generated by Django 2.0.13 on 2019-06-14 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0029_auto_20190613_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='CategoryID',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Name', on_delete=django.db.models.deletion.CASCADE, to='stronka.Category'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='Group',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 14, 8, 51, 36, 919179)),
        ),
    ]
