# Generated by Django 2.0.13 on 2019-06-16 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0030_auto_20190614_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='Group',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 16, 21, 9, 14, 198075)),
        ),
    ]
