# Generated by Django 2.0.13 on 2019-06-18 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0033_auto_20190617_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 18, 9, 41, 17, 876175)),
        ),
    ]
