# Generated by Django 2.0.13 on 2019-06-18 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stronka', '0034_auto_20190618_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='Register_Date',
            field=models.DateField(default=datetime.datetime(2019, 6, 18, 9, 47, 21, 754263)),
        ),
    ]
